/**
 * Options shared by all AI provider completions.
 * Mirrors the existing CompletionOptions in ai.service.ts so callers
 * can be migrated one-by-one without breaking changes.
 */
export interface CompletionOptions {
  /** Sampling temperature (0–2). Defaults to provider-specific value. */
  temperature?: number;
  /** Upper bound on tokens to generate. Defaults to provider-specific value. */
  maxTokens?: number;
  /** Optional system / instruction prompt prepended to the conversation. */
  systemPrompt?: string;
}

/**
 * Canonical identifier for a supported AI provider.
 * Extend this union when adding a new provider.
 *
 * @example
 * const provider: AiProviderName = 'openai';
 */
export type AiProviderName = 'openai' | 'anthropic' | 'google' | 'mock';

/**
 * Metadata that every concrete provider implementation must expose.
 * Used for logging, health-checks, and dynamic selection at runtime.
 */
export interface AiProviderInfo {
  /** The canonical name of this provider. */
  name: AiProviderName;
  /** Human-readable model identifier, e.g. "gpt-4o-mini" or "claude-3-haiku". */
  model: string;
  /** Whether the provider is ready to serve requests (API key present, etc.). */
  isAvailable: boolean;
}

/**
 * `AiProvider` — the contract every AI backend must satisfy.
 *
 * Implement this interface (and mark the class `@Injectable()`) to plug a new
 * model provider into the RentAI AI layer without touching existing services.
 *
 * @example
 * ```ts
 * @Injectable()
 * export class OpenAiProvider implements AiProvider {
 *   readonly info: AiProviderInfo = { name: 'openai', model: 'gpt-4o-mini', isAvailable: true };
 *
 *   async generateCompletion(prompt: string, options: CompletionOptions): Promise<string> {
 *     // ...
 *   }
 * }
 * ```
 */
export interface AiProvider {
  /** Static metadata about this provider instance. */
  readonly info: AiProviderInfo;

  /**
   * Generate a single-turn text completion.
   *
   * @param prompt   The user-facing input / question.
   * @param options  Optional temperature, token limit, and system prompt.
   * @returns        The raw text generated by the model.
   * @throws         If the provider is unavailable or the request fails.
   */
  generateCompletion(
    prompt: string,
    options?: CompletionOptions,
  ): Promise<string>;
}

/**
 * NestJS injection token for the active `AiProvider`.
 * Use this token in `@Inject()` decorators and module `provide` arrays.
 *
 * @example
 * constructor(@Inject(AI_PROVIDER_TOKEN) private provider: AiProvider) {}
 */
export const AI_PROVIDER_TOKEN = 'AI_PROVIDER' as const;
